/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE PREARM_FLAG PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* prearm error flag
*/
public class msg_prearm_flag extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_PREARM_FLAG = 228;
    public static final int MAVLINK_MSG_ID_PREARM_FLAG_CRC = 24;
    public static final int MAVLINK_MSG_LENGTH = 8;
    private static final long serialVersionUID = MAVLINK_MSG_ID_PREARM_FLAG;


      
    /**
    * timestamp millis
    */
    public long time;
      
    /**
    * prearm_error_flag
    */
    public long value;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_PREARM_FLAG;
        packet.crc_extra = MAVLINK_MSG_ID_PREARM_FLAG_CRC;
              
        packet.payload.putUnsignedInt(time);
              
        packet.payload.putUnsignedInt(value);
        
        return packet;
    }

    /**
    * Decode a prearm_flag message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time = payload.getUnsignedInt();
              
        this.value = payload.getUnsignedInt();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_prearm_flag(){
        msgid = MAVLINK_MSG_ID_PREARM_FLAG;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_prearm_flag(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_PREARM_FLAG;
        unpack(mavLinkPacket.payload);
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_PREARM_FLAG - sysid:"+sysid+" compid:"+compid+" time:"+time+" value:"+value+"";
    }
}
        