/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE EVENT_ACK PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* prearm error flag
*/
public class msg_event_ack extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_EVENT_ACK = 330;
    public static final int MAVLINK_MSG_ID_EVENT_ACK_CRC = 147;
    public static final int MAVLINK_MSG_LENGTH = 6;
    private static final long serialVersionUID = MAVLINK_MSG_ID_EVENT_ACK;


      
    /**
    * timestamp millis
    */
    public long time;
      
    /**
    * 
    */
    public short sequence;
      
    /**
    * 
    */
    public short result;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_EVENT_ACK;
        packet.crc_extra = MAVLINK_MSG_ID_EVENT_ACK_CRC;
              
        packet.payload.putUnsignedInt(time);
              
        packet.payload.putUnsignedByte(sequence);
              
        packet.payload.putUnsignedByte(result);
        
        return packet;
    }

    /**
    * Decode a event_ack message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time = payload.getUnsignedInt();
              
        this.sequence = payload.getUnsignedByte();
              
        this.result = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_event_ack(){
        msgid = MAVLINK_MSG_ID_EVENT_ACK;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_event_ack(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_EVENT_ACK;
        unpack(mavLinkPacket.payload);
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_EVENT_ACK - sysid:"+sysid+" compid:"+compid+" time:"+time+" sequence:"+sequence+" result:"+result+"";
    }
}
        