/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Very important event type
*/
public class VIP_EVENTS_TYPE {
   public static final int MAV_VIP_EVENT_ERROR = 0; /*  | */
   public static final int MAV_VIP_EVENT_COMMON = 1; /*  | */
   public static final int VIP_EVENTS_TYPE_ENUM_END = 2; /*  | */
}
            