/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class VIP_EVENTS_NAME {
   public static final int MAV_VIP_EVENT_RC_LOST = 0; /*  | */
   public static final int MAV_VIP_EVENT_LOW_YW = 1; /*  | */
   public static final int MAV_VIP_EVENT_LOW_POWER = 2; /*  | */
   public static final int MAV_VIP_EVENT_TAKEOFF_ARMING_ERROR = 3; /*  | */
   public static final int MAV_VIP_EVENT_TAKEOFF_SET_STABLIZE_ERROR = 4; /*  | */
   public static final int MAV_VIP_EVENT_TAKEOFF_SET_AUTO_ERROR = 5; /*  | */
   public static final int MAV_VIP_EVENT_TAKEOFF_SUCCESS = 6; /*  | */
   public static final int VIP_EVENTS_NAME_ENUM_END = 7; /*  | */
}
            